### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by benjello** [cbenz/openfisca-interactive#2]
When running:
```
(openfisca-interactive) benjello@msika:~/openfisca/openfisca-interactive(master=)$ jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
An error occured.
ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-ziit9uu0.log
```

I got this in /tmp/jupyterlab-debug-ziit9uu0.log

```
Node v10.15.2

> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at evalmachine.<anonymous>:44:31
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

Traceback (most recent call last):

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/commands.py", line 1373, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "/home/benjello/.virtualenvs/openfisca-interactive/lib/python3.7/site-packages/jupyterlab/commands.py", line 1444, in _extract_package
    raise ValueError(msg % source)

ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package

Exiting application: jupyter
```

**Comment by benjello** [comment]
I did not retry. I will close and reopen if needed.
